### PR TITLE
Fix lat/long and pop dialog when returning from observation

### PR DESCRIPTION
**Pull request by hundredball**
## Main changes
- Show user's current lat/long in observation page when uploading observation instead of (0,0)
- When user returns from observation page or upload session page, a dialog will pop up to ask user whether they want to leave without saving.

### CODE REVIEW

**Comment by mfrants** [comment]
Hi Chieh

I checked out the bugfix/lat_long branch today and tried it out (using the
Android simulator).  The pop-up dialog works fine, but lat and long on the
observation page are still showing zeros rather than current location.  Is
this because I'm running on a simulator rather than an actual phone?  Is
there a way I can test it out?  The code looks good to me.

Marina Frants
Information Manager, CCE-LTER and CalCOFI
Scripps Institution of Oceanography
***@***.***

**Comment by hundredball** [comment]
Thanks for testing, Marina! I used an Android simulator as well. You can set the location of the emulator from the following steps. It should also reflect on the map page. 
Screen Shot 2023-02-27 at 11 29 54 PM

**Comment by hundredball** [comment]
Hi Marina, I made two other changes when I tried to run app on iOS simulator.
- Modify iOS bundle identifier as org.calcofi.ovewview, also add app with new identifier on Firebase
- Add alert dialog for timeline page, without it, pressing return button on timeline page will navigate to upload page directly

**Comment by mfrants** [comment]
Hi Chieh

I've moved the Log Out function from the welcome page to the profile page.
Since it's a very small change, I pushed it into the same lat/long bug fix
branch.

However, I'm still unable to get the lat long to show up in my upload
screen.  I followed the instruction in the link you found (
https://stackoverflow.com/questions/2279647/how-to-emulate-gps-location-in-the-android-emulator),
but the Send button on the location screen has no effect for me.  I think
the problem is somewhere in my local machine configuration rather than in
your code, so if it's working for you, I think it's okay to go ahead and
merge the pull request.
Marina Frants
Information Manager, CCE-LTER and CalCOFI
Scripps Institution of Oceanography
***@***.***

**Comment by hundredball** [comment]
Hi Marina, I tested it on TestFlight and it also showed `0,0`. I will need to do further testing on iOS device.

**Pull request merged**
