### PR TITLE
Timeout check and null return value check for image and text search

### PR DESCRIPTION
**Pull request by mfrants**
Hi Chieh

I've added time outs for both types of searches on the uploads page.  The one for text search was fairly straightforward, because it uses a Future, but the one for image search was tricky because it uses a MultiPartRequest, and I couldn't find a clean way to handle a timeout for that.  I finally got something to work, but it's pretty kludgy.  If you come up with a better method, feel free to change it.

I've found that the best way to test this is to set the timeout duration to something really small, like 5 milliseconds, and try a search.

### CODE REVIEW

**Comment by hundredball** [comment]
I typed cat and in the terminal, it actually found some results but showed not found on the emulator.

**Comment by mfrants** [comment]
Hi Chieh

I’ll try to get to it on Monday or Tuesday.

Marina Frants (she/her/hers)
Information Manager, CCE-LTER/CalCOFI
Scripps Institution of Oceanography, La Jolla, CA
***@***.***

**Comment by mfrants** [comment]
Hi Chieh

I just pushed a fix for this.

Marina Frants
Information Manager, CCE-LTER and CalCOFI
Scripps Institution of Oceanography
***@***.***

**Comment by hundredball** [comment]
Thanks, Marina! This fix works for me as well. I also did a small change to fix the back button on the text search page. If you don't mind, I can also push it to this branch.

**Comment by mfrants** [comment]
Hi Chieh

Yes, please go ahead and push.

Marina Frants
Information Manager, CCE-LTER and CalCOFI
Scripps Institution of Oceanography
***@***.***

**Comment by hundredball** [comment]
Hi @mfrants, I just pushed the fix for it. If that also works for you, you can merge this PR. 
I thought we would still have a meeting today. Do you have any topics that would like to hand over to me before your trips?

**Comment by mfrants** [comment]
Hi Chieh

Sorry, I got into zoom a few minutes late.  I can talk now if you want, but
actually I think we're in good shape, so unless there's anything you want
to go over, we can skip the meeting tonight.

Marina Frants
Information Manager, CCE-LTER and CalCOFI
Scripps Institution of Oceanography
***@***.***

**Pull request merged**
